### ISSUE TITLE
Getting the currently set language

### ISSUE THREAD

**Issue by TheDutchCoder** [pespantelis/vue-localizer#1]
Is there a way to get the current language?
I would need access to it for e.g. formatting prices and it would be helpful if I didn't have to store in somewhere in my global state.

Thanks!

**Comment by pespantelis** [comment]
At this time no, I missed that.
But I'll add a `get` method to support this.

``` js
$lang.get()
```

Thanks for the interest! :)

**Comment by TheDutchCoder** [comment]
Cool, would be very useful, thanks
