### ISSUE TITLE
'$ {amount}' with amount being 0 returns '$ {amount}' instead of '$ 0'

### ISSUE THREAD

**Issue by TheDutchCoder** [pespantelis/vue-localizer#2]
Seems to be a bug, where if the value '0' (Number) is passed in, the plugin will return the original string, instead of the replaced string.

**Comment by pespantelis** [comment]
I suppose you have tried this:

``` js
// text = '$ {amount}'
$lang('your.path', amountValue)
```

Instead of this:

``` js
// text = '$ {amount}'
$lang('your.path', {amount:amountValue})
```

Also you could try this:

``` js
// text = '$ {0}'
$lang('your.path', [amountValue])
```

**Comment by TheDutchCoder** [comment]
Can you please reopen this issue?
Neither of the suggested options work, all of them keep returning `$ {amount}` instead of `$ 0`

**Comment by pespantelis** [comment]
Could you provide a piece of code?

**Comment by TheDutchCoder** [comment]
``` JS
{{ $lang('price', { amount: price }) }}

// My component locales.
locales: {

  en: {
    price: '$ {amount}',
    tax: 'Plus tax'
  },

  fr: {
    price: '{amount} $',
    tax: 'Avec tax'
  }

},

// In cases where price === 0 it will print '$ {amount}' instead of '$ 0'
```

**Comment by TheDutchCoder** [comment]
It works when '0' is provided as a String, but fails if it's a Number.

**Comment by pespantelis** [comment]
Oh now I understand your point, you are right!
I'll check it, thanks!

**Comment by TheDutchCoder** [comment]
Coll thanks!

**Comment by TheDutchCoder** [comment]
I've upgraded to 1.1.0, but this issue is still there.

**Comment by pespantelis** [comment]
Oh sorry, I forget to update the `dist` folder.

**Comment by pespantelis** [comment]
Ok ;)

**Comment by TheDutchCoder** [comment]
Still no luck :/

**Comment by pespantelis** [comment]
It works for me (v1.1.1), check it again please :)

**Comment by TheDutchCoder** [comment]
It doesn't ;-)

```
{{{ $lang('price', { amount: price }) }}} {{ typeof price }}
```

Results:
String:

```
$0 string
```

Number:

```
${amount} number
```

**Comment by pespantelis** [comment]
Check this:
http://www.webpackbin.com/EkWkaZXW-

**Comment by TheDutchCoder** [comment]
Alright, it worked after hard uninstalling and re-installing, just not after upgrading with npm.
Thanks!
